- .github/workflows/maven.yml
Creates an initial version of a public shared Maven workflow for review and testing, this is based off our private shared Maven workflow and modified as so:    
- Remove unnecessary permissions as public version of the workflow does not need `id-token: write` permissions
- Remove AWS steps related to private infrastructure
- Improve how credentials are exported to environment by exporting them at the job level rather than via a specific job step
- Uses latest checkout and setup-java action versions
> Add a shared Maven Build workflow

- .github/workflows/jira-sync.yml
Adds a workflow that can be used to automate the process of having any issues opened on a public repository also get sync'd to JIRA for tracking purposes.
Individual repositories can then add a workflow that calls this e.g. https://github.com/telicent-oss/jira-sync/blob/main/.github/workflows/jira-sync.yml and runs whenever a new issue is created e.g. https://github.com/telicent-oss/jira-sync/actions/runs/8453726009
> Prototype JIRA Sync workflow

- .github/workflows/maven.yml
Make it more flexible by allowing GPG key and passphrase to be omitted in which case GPG signing, and `SNAPSHOT` publishing, is disabled.
Make it stricter about when we publish `SNAPSHOT`s, GPG signing **MUST** be enabled for this to happen, and the triggering actor **MUST NOT** be Dependabot.
> Improve the Maven Workflow

- .github/workflows/jira-sync.yml
Fixing a couple of bugs noted when starting to try and use this workflow more widely:
- `issues: write` permission is needed so that we can close issues after sync and leave a comment indicating where the issue is now tracked in JIRA
- Also explicitly pass `GITHUB_TOKEN` secret into `to-jira` command otherwise the called workflow can't read issues from the supplied GitHub repository unless it is a public repository
> Explicitly pass GITHUB_TOKEN to sync step

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/maven.yml
- .github/workflows/trivy-image-scan.yml
Adds Trivy scanning to the shared Maven and Docker workflows.
Also adds GitHub release generation to the Maven workflow.
> Enable vulnerability scanning (CORE-244, CORE-258)

- .github/workflows/maven.yml
- Fixes a piece of missing configuration for the Maven Server that could cause a release to fail to deploy successfully.
- Also corrects the name of the secrets being referenced to match the actual organisation secrets
> Fix Maven Server configuration

- .github/workflows/python-gh-release.yml
Tested against [Telicent-lib/CHANGELOG.md](https://github.com/telicent-oss/telicent-lib/blob/main/CHANGELOG.md) versions 2.0.0, 2.0.2 and another test repository containing single release in `CHANGELOG.md`
---
2.0.0 The initial release of telicent-lib
---
```bash
Detected Release Notes for 2.0.0 are:
* initial release ([c605ee7](https://github.com/telicent-oss/telicent-lib/commit/c605ee76a5dea86585112620b4350855d527ccc5))
```
---
2.0.2 A bug fix version
---
```bash
Run RELEASE="2.0.0"
Detected Release Notes for 2.0.0 are:
* initial release ([c605ee7](https://github.com/telicent-oss/telicent-lib/commit/c605ee76a5dea86585112620b4350855d527ccc5))
```
----
Test repository
----
```bash
* init relese test ([838fcd4](https://github.com/gnikolov95/test-gh-release/commit/838fcd454bc9cc60a53940653ac …
```
> chore: handle release notes extraction better

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/maven.yml
- README.md
- docs/maven.md
- isMavenCentralReady.sh
- Added optional `MAVEN_DEBUG_ARGS` based on @TelicentPaul's approach
- Improved self-documentation of inputs in Maven Workflow
- Default JDK now upgraded to 21
- Docker Workflow can now trigger a quick Maven build prior to the Docker build
- Added developer documentation for Maven workflow
- Allow a recently introduced step in the Docker build workflow to be skipped when it isn't applicable to how a team produces SBOMs
> Various improvements to Maven Workflow (CORE-291)

- .github/workflows/docker-push-to-registries.yml
Dependabot triggered builds have access to a much reduced set of secrets meaning that they can only read images from our DockerHub and not push them.  Thus set the value of the push input to `true` **only** when the actor for a build is not Dependabot
Example Dependabot triggered build that fails because of this - https://github.com/telicent-oss/smart-caches-core/actions/runs/9496984988/job/26303783168
> Dependabot Triggered Builds don't try to push images

- isMavenCentralReady.sh
If the Maven property isn't defined mvn just echos the property expression as-is without the value being interpolated which meant it incorrectly passed the sanity check.  Now double check for this case and fail the sanity check if so.
Discovered with @TelicentPaul as he was working through his first attempt at the open source release process
> Additional checks on Maven properties

- .github/workflows/docker-push-to-registries.yml
As Dependabot triggered builds only have read credentials for the Docker Hub registry they already don't push the built images.  However, this means that when the scan image workflow is triggered it tries to pull a non-existent image and fails.
For example see https://github.com/telicent-oss/smart-caches-core/actions/runs/9553292061/job/26332421007
Thus we now skip the image scan workflow for Dependabot builds.
> Dependabot skips Image Scans

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/trivy-dockerfile-scan.yml
Adds a new shared workflow for Dockerfile misconfiguration scanning and ensures it is invoked from the `shared docker-push-to-registries.yml` workflow
This is a pretty straightforward copy paste of the workflow that was already introduced for private builds with minor changes to adapt for slightly different input names
> Enable Dockerfile misconfiguration scanning (CORE-335)

- .github/workflows/maven.yml
- .github/workflows/python-gh-release.yml
Move the hacky script and steps into a separate composable action that can be used as a single step within a workflow and provides usable outputs
Modified Maven and Python release workflows to use the reusable action
- Needs https://github.com/telicent-oss/extract-release-notes-action/pull/4 to be merged to align reusable action behaviour with the inline scripts being replaced
> Extract release notes better

- .github/workflows/maven-cache-dependencies.yml
- .github/workflows/maven-github-release.yml
- .github/workflows/maven.yml
- .github/workflows/parallel-maven.yml
- docs/maven.md
Similar to what's already been done for private workflows this adds a parallel Maven build workflow.  This can speed up builds for larger repositories significantly as build time is determined by the slowest building module, not the total build time of all modules.
Tested on https://github.com/telicent-oss/smart-caches-core/actions/runs/10698176791 (our current slowest building open source Java repository) and gave a ~10 minute reduction in build time
> Adds a Parallel Maven Build workflow

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/python-push-to-registries.yml
It was noticed that OSS repositories didn't seem to be producing OSS images correctly, on digging it was spotted that these were missing the necessary QEMU setup step present in the internal versions of this workflow.  Adding this step should allow OSS repositories to generate valid multi-platform images.
> Add missing QEMU setup to Docker workflows (TELDEVOPS-374)

- .github/workflows/maven-github-release.yml
Adds a new step to the Maven GitHub Release workflow so that on successful release it will create a Release PR that completes the release process.  This avoids the need for developers to manually open said PRs and reduces the chance that these get missed.
Note no reviewers are assigned, rather we'll rely on default reviewers which are populated from `CODEOWNERS` if present which it mostly isn't currently, but something we can address over time.
> Auto-create Maven Release PRs

- .github/workflows/dockerhub-vulnscan-image.yml
- .github/workflows/grype-image-scan.yml
- .github/workflows/python-scan-sbom.yml
Fixes an issue with grype not being able to recognise CycloneDX generated sbom as a valid one.
> fix: grype erroring with invalid sbom

- .github/workflows/maven-github-release.yml
As seen in SCG build if the developer is proactive in creating the Release PR, or it already exists for some other reason, then this breaks the build and causes artefacts to not be correctly published.  Make the Release PR step continue-on-error: true so that failures in that step are ignored.
> Make opening Maven Release PR not break build

- .github/workflows/javascript-test-feature-branch.yml
Adds a workflow input for the js "test command"
e.g. `yarn test`  or `yarn test:ci`
Is in use by Telicent access: https://github.com/search?q=org%3Atelicent-oss%20javascript-test-feature-branch%2Fyarn-test-command&type=code
> feat(javascript-test-feature-branch.yml): yarn-test-command

- .github/workflows/maven.yml
- .github/workflows/parallel-maven.yml
- .github/workflows/python-generate-image-sbom.yml
- .github/workflows/trivy-dockerfile-scan.yml
- .github/workflows/trivy-image-scan.yml
- .github/workflows/vulnerability-scanning-on-repo.yml
Changing trivy cache key prefix to address intermittent Trivy scan failures in the workflows.
See [here](https://github.com/Telicent-io/pipeline-entity-extraction/actions/runs/11274705737/job/31355224725) for example.
> ci: change trivy cache prefix

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/grype-image-scan.yml
- .github/workflows/trivy-image-scan.yml
Despite dragging my feet hoping docker node would fix their CVE - they have not.
(I'm going to side step the issue _for now_)
If we have CVEs in the _build_ image, they can be easily explained away. So it is worth turning off certain CVEs - only in build images.
Obviously this is relying on convention/documentation to ensure people don't ignore important CVEs, not ideal but not terrible.
> feat: cve ignore for build images

- .github/workflows/maven.yml
This was implemented in Telicent Test (see below) but is lacking here.
It is needed for known issue with Windows file system. 
https://github.com/Telicent-io/telicent-test/issues/146
https://github.com/Telicent-io/telicent-test/pull/147
> [GH-146] Allow flag to enable/disable windows build

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/grype-image-scan.yml
- .github/workflows/trivy-image-scan.yml
This change bring in the ability to run the same build flow where frontend and javascript code can be built in the CI and then the build artifacts are built into the container. This has significantly reduced the build time within the closed source apps (in one case from an hour to approx. 12 minutes) including scanning. 
A second change in this PR allows for the option to "dry run" the build of the containers, so that the workflow can build and then scan without pushing to Docker. This has only been test with the frontend app, but should work for other docker builds and should also not impact any existing workflows. 
NB: I will be squashing before I merge, got bored with one line change commits to try things out.
> Update work flow for quicker front end builds and scanning 

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/grype-image-scan.yml
Option to make Grype only error if fix is available 
* Option defaults to false
* Setting to true brings Grype inline with Trivvy
* before option: https://github.com/telicent-oss/telicent-access/actions/runs/13197098865 Fails correct
* option is true: https://github.com/telicent-oss/telicent-access/actions/runs/13200569330 Passes
* Once merged will run:
* option is false: https://github.com/telicent-oss/telicent-access/actions/runs/13202761299 (should run and fail once merged) 🚧 
🚨 **THIS OPTION WON"T BE USED BY ANY CODE IN MAIN**🚨
> fix: Option to make Grype only error if fix is available

- .github/workflows/trivy-image-scan.yml
Trivyignore files should be used instead when CVE is accepted. Option to skip unfixed is still available via parameter if required for other scan use cases.
> ci: remove default behaviour of passing job if CVEs are unfixed

- .github/workflows/maven.yml
For testing purposes initially, so only applying to maven.yml at present
> [CORE-754] Adding Jacoco Code Coverage Reports as artifacts for the build.

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/maven.yml
- .github/workflows/parallel-maven.yml
- .github/workflows/trivy-dockerfile-scan.yml
- .github/workflows/trivy-image-scan.yml
This is the initial conversion of some of the shared workflows to use the new Telicent Trivy action which allows simplyfying chunks of the existing shared workflows to a single step.  Due to the reductive nature of this PR you may find it best viewed using Split rather than Unified diff mode.
Note I have intentionally limited this change to the existing usages that are primarily relevant for the Platform team, though some of the common Docker workflows are changed which will affect other teams (but hopefully don't break anything!).  I expect that other teams may want to adapt their workflows to adopt this in the future but didn't want to try and do that for you in one giant PR.  Plus there are some usages that might require enhancements to the new action before they can be switched over. …
> Initial adoption of Telicent Trivy action (TELDEVOPS-591)

- .github/workflows/maven.yml
- .github/workflows/parallel-maven.yml
As a follow-up to https://github.com/telicent-oss/shared-workflows/pull/104
And also correcting typo.
> fix: [CORE-754] Adding Jacoco Code Coverage Reports as artifacts for the parallel build

- .github/workflows/maven.yml
- .github/workflows/parallel-maven.yml
- docs/maven.md
Initial introduction of public image caching into Maven builds, this aims to avoid hitting rate limits on image pulls and speed up builds.
Tested at https://github.com/telicent-oss/smart-caches-core/actions/runs/14195626524
Obviously no actual caching has happened yet as that isn't on the `main` branch and the workflow is configured to only pull images and populate the cache from the `main` branch.  But this verifies that the new jobs and job steps are present and functioning correctly.  Once this is merged I can get the relevant PR merged in that sets the `PUBLIC_IMAGES` input and verify that images are actually getting cached.
> Add public image caching to Maven builds (CORE-752)

- .github/workflows/maven.yml
- .github/workflows/parallel-maven.yml
- .github/workflows/trivy-image-scan.yml
Updates usage of our `telicent-oss/trivy-action` to use the new `remote-vex` input feature.  In particular for Docker builds this ensures that we pick up VEX statements from the base images repository by default so a vulnerability assessed and determined to not affect us in the base images isn't flagged in every downstream repository
> Enable Remote VEX statements (TELDEVOPS-589)

- .github/workflows/docker-push-to-registries.yml
- .github/workflows/jira-sync.yml
- .github/workflows/maven-cache-dependencies.yml
- .github/workflows/maven-github-release.yml
- .github/workflows/maven.yml
- .github/workflows/parallel-maven.yml
Use the latest `actions/setup-java` to avoid issues with deprecated Actions Cache APIs
> Update to latest actions/setup-java

- .github/workflows/trivy-image-scan.yml
We are seeing trivy failures in Releases
https://github.com/telicent-oss/smart-cache-graph/actions/runs/15023460880/job/42219235178
This mimics
https://github.com/telicent-oss/telicent-base-images/pull/177
> fix: Do not propagate TRIVY_VEX env variable

- .github/workflows/python-create-release-pr.yml
- .github/workflows/python-gh-release.yml
Change to allow projects to override the python/pyproject.toml options of release please with rust/Cargo.toml for our Rust based Python libraries.
An alternative approach would have been to make whole new workflows for Rust, but this option seemed like the easier to maintain (fewer .yml files).
Example usage: https://github.com/Telicent-io/rusty-pdp/blob/main/.github/workflows/create-release-pr.yml
> chore(python): support rust based python libraries
